[package]
name = "code_samples"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
async-trait = "0.1.83"
cooptex = "0.2.1"
mockall = "0.13.0"
serde = {version = "1.0.211", features = ["derive"]}
serde_json = "1.0.132"
tokio = { version = "1.29", features = ["macros", "rt"] }
uuid = "1.11"
